/*
 * Hello Service
 *
 * A hello world service.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// HelloHello - hello hello
func HelloHello(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// HelloOpenapiJson - Download ./gen/http/openapi.json
func HelloOpenapiJson(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
